import Head from 'next/head'
import Header from './Sections/Header';
import Footer from './Sections/Footer';

function Layout({ title, children }) {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                {children}
            </main>

            <Footer />

        </div>
    );
}

export default Layout;